package com.vitalis.data.entity

import com.vitalis.common.enums.Role
import jakarta.persistence.*
import org.springframework.security.core.GrantedAuthority
import java.util.UUID

@Entity
@Table(name = "roles")
class Role(
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    var id: UUID? = null, // Nullable UUID for the autogenerated ID

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, unique = true)
    var name: Role // Reference to the enum type for role name
) : GrantedAuthority {

    // Default constructor for JPA
    constructor() : this(name = Role.ROLE_DEFAULT) // Default to USER role or any other suitable role

    override fun getAuthority(): String {
        return name.name // Return the enum name as the authority
    }
}
